### DISCUSSION TITLE
I want to be able to set header and footer only for page 2 and following

### DISCUSSION THREAD

**Discussion by HarryJulsing** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#74] [Q&A] [answered]
The administrator shall be able to configure the exporter to start the header and footers from page 2.
 
We have a custom document front page, which does not require a header and footer for this front page. 
We cannot use the front page facility of the PDF exporter. 

Is there a way to configure the CSS to make this happen?

**Comment by Jumas** [comment, marked as answer]
Hi HarryJulsing,

you can achieve this just by adding following css in the settings:
```css
@page :first {
    border-bottom: none;
    @top-left {
        content: "";
    }
    @top-center {
        content: "";
    }
    @top-right {
        content: "";
    }
    @bottom-left {
        content: "";
    }
    @bottom-center {
        content: "";
    }
    @bottom-right {
        content: "";
    }
}
```
