### ISSUE TITLE
Hide content in PDF export

### ISSUE THREAD

**Issue by schlami** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#342]
### Description

So far we are using a custom wiki code to create the title page in our documents. This title page is being converted to PDF by the Polarion export to PDF function. To be able to use your PDF exporter, I would like to hide the custom wiki code, so it's not converted to PDF by this exporter. Is this possible somehow? In Polarion it's possible to hide content from being shown in PDFs by wiki command {show:wiki}, but this command will hide the content in this exporter but also in Polarion's exporter. Could there be another command which would hide some content only when your exporter is used?

If this is not possible, could you add an option to skip the cover page creation completely and to add just a blank page instead (without header and footer)? Then we could continue to use the custom script to create the title page.

### Motivation

 see above

**Comment by ralfsmolarek3** [comment]
Our aim is to make the PDF-Exporter as compatible as possible. Therefore the wiki macros work in the same way for the internal PDF-exporter and ours.
If the wiki-block has any specific id, it should be possible to exclude it using CSS, but finding it out is ugly (if it is only a table this might be easier, but for more complex printouts IMO not).
As the use-case is clear, maybe we can set a variable on execution of PDF-exporter which can be checked... we will check.

**Comment by Jumas** [comment]
There is a simple way to hide all wiki blocks from the resulting pdf by using following css without hardcoding any specific IDs:
```css
.polarion-dle-wiki-block {
    display: none;
}
```

Alternatively you can hide only the first wiki block:
```css
.polarion-dle-wiki-block:not(.polarion-dle-wiki-block ~ .polarion-dle-wiki-block) {
    display: none;
}
```

As for the leading blank page - you can just create empty cover page like this one:
![Image](https://github.com/user-attachments/assets/bfc588e4-bd40-4eec-aadd-0b12391054db)
so the result will be completely empty page.

@schlami 
Does this solves your issues?

**Comment by Jumas** [comment]
> Where would I put this CSS?

In the project's administration pane -> PDF Export -> CSS:
![Image](https://github.com/user-attachments/assets/09ec34a5-173b-44cd-ad0d-2a9f0aeca08c)

> If this css goes anywhere in Polarion, the wiki block would be always skipped not just when converted by SBB PDF exporter.

This CSS will be applied during SBB PDF export only.

>If there was a possibility to hide the footer and the header for x pages, this would probably help

There was already discussion about this (https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/discussions/74#discussioncomment-10020668).
If you need to hide header/footer not just on the first page then you can use something like this:
```css
@page :nth(1), :nth(2), :nth(3) {
    border-bottom: none;
    @top-left {
        content: "";
    }
    @top-center {
        content: "";
    }
    @top-right {
        content: "";
    }
    @bottom-left {
        content: "";
    }
    @bottom-center {
        content: "";
    }
    @bottom-right {
        content: "";
    }
}
```
